Style/StringLiterals:
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 100  

Style/StringLiteralsInInterpolation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Enabled: false