source "https://rubygems.org"

gem "allure-cucumber"
gem "appium_lib"
gem "browserstack-local"
gem "cucumber"
gem "dotenv-vault"
gem "puma"
gem "rspec"
gem "rubocop"
gem "ruby-lsp"
gem "rufo"
gem "selenium-webdriver"
gem "sinatra"
gem "yaml"
