source 'https://rubygems.org'

gem 'allure-cucumber'
gem 'appium_lib'
gem 'appium_lib_core'
gem 'browserstack-local'
gem 'cucumber'
gem 'dotenv'
gem 'dotenv-vault'
gem 'puma'
gem 'rspec'
gem 'rubocop'
gem 'selenium-webdriver'
gem 'sinatra'
gem 'yaml'
