name: Pipe

on:
  push:
  pull_request:
    branches:
      - main
  
  schedule:
    - cron: '0 12,15,18 * * 1-5'  

jobs:
  tests-e2e:
    runs-on: ubuntu-latest
    steps:
    - name: run checkout project
      uses: actions/checkout@v3
    
    - uses: actions/checkout@v4
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.3'

    - name: Install dependencies
      run: bundle install

    - name: Rubocop verify
      run: rubocop
   
    - name: Run tests
      env:
        BS_USER: ${{ secrets.BS_USER }}
        BS_KEY: ${{ secrets.BS_KEY }}
        BS_HASH: ${{ secrets.BS_HASH }}
      run: bundle exec cucumber t=bs 

    - name: Get Allure history
      uses: actions/checkout@v2
      if: always()
      continue-on-error: true
      with:
        ref: gh-pages
        path: gh-pages
    
    - name: Allure Report action from marketplace
      uses: simple-elf/allure-report-action@master
      if: always()
      id: allure-report
      with:
        allure_results: ./output
        gh_pages: gh-pages
        allure_report: allure-report
        allure_history: allure-history
        
    - name: Deploy report to Github Pages
      if: always()
      uses: peaceiris/actions-gh-pages@v2
      env:
        PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: allure-history