name: Pipe

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  tests-e2e:
    runs-on: ubuntu-latest

    steps:
    - name: run checkout project
      uses: actions/checkout@v3
    
    - name: Set up Ruby
      uses: ruby/setup-ruby@55283cc23133118229fd3f97f9336ee23a179fcf
      with:
        ruby-version: 3.0
        bundler-cache: true
   
    - name: Run tests
      env:
        BS_USER: ${{ secrets.BS_USER }}
        BS_KEY: ${{ secrets.BS_KEY }}
        BS_HASH: ${{ secrets.BS_HASH }}
        DEVICE: ${{ secrets.DEVICE || 'Google Pixel 3' }}
      run: bundle exec cucumber t=bs

    - name: Get Allure history
      uses: actions/checkout@v2
      if: always()
      continue-on-error: true
      with:
        ref: gh-pages
        path: gh-pages
    
    - name: Allure Report action from marketplace
      uses: simple-elf/allure-report-action@master
      if: always()
      id: allure-report
      with:
        allure_results: ./output
        gh_pages: gh-pages
        allure_report: allure-report
        allure_history: allure-history
        
    - name: Deploy report to Github Pages
      if: always()
      uses: peaceiris/actions-gh-pages@v2
      env:
        PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: allure-history