name: Pipe

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  tests-e2e:
    runs-on: ubuntu-latest

    steps:
    - name: run checkout project
      uses: actions/checkout@v3
    
    - name: Set up Ruby
      uses: ruby/setup-ruby@55283cc23133118229fd3f97f9336ee23a179fcf
      with:
        ruby-version: 3.0
        bundler-cache: true
   
    - name: Run tests
      run: bundle exec cucumber
